### ISSUE TITLE
Run in Docker

### ISSUE THREAD

**Issue by nikitosl** [go-echarts/snapshot-chromedp#14]
Hello! Really nice lib for generating charts on go and nice tool to make it in .png format!
Script works perfect locally, but when I am trying to wrap it into docker container, that issue appears:
`"error":"exec: \"google-chrome\": executable file not found in $PATH"`
I have added `github.com/chromedp/chromedp` to vendor as well.
May be someone else met this problem? Do I need to install chrome to my image? 
Thanks for any ideas!!

**Comment by Koooooo-7** [comment]
Hi @nikitosl ，yes, we need a Chrome runtime in the container.
Alternatively, in the CI, I use the [docker-headless-shell](https://github.com/chromedp/docker-headless-shell), you could take a look on it. I suppose you could have a `docker-compose` including it should work fine.
