### ISSUE TITLE
Can not render image from manually output stream bytes content.

### ISSUE THREAD

**Issue by hw524926** [go-echarts/snapshot-chromedp#15]
barTitleChart := DysSafetyAssessmentService.PieTitle(dangerMap, title)
// barTooltipChart := barTooltip()
barTitleChartBuf := new(bytes.Buffer)
err := barTitleChart.Render(barTitleChartBuf)
if err != nil {
   return err
}
err = render.MakeChartSnapshot(barTitleChartBuf.Bytes(), filePath)
if err != nil {
   return err
}
return nil

**Comment by Koooooo-7** [comment]
Hi @hw524926 , you could have a try like this:
```go
// I suppose it is your bar chat
barTooltipChart := barTooltip()
render.MakeChartSnapshot(barTooltipChart.RenderContent(), "my-chart.png")
```
