### ISSUE TITLE
Option to return imgContent []byte instead of writing to file

### ISSUE THREAD

**Issue by jpyen** [go-echarts/snapshot-chromedp#16]
Planning to raise a PR to add an option to get the chart imgContent for further processing instead of writing it to file.

Any thoughts or concerns?

**Comment by Koooooo-7** [comment]
> Planning to raise a PR to add an option to get the chart imgContent for further processing instead of writing it to file.
> 
> Any thoughts or concerns?

Could you provide the reason/assumption of y we need this?

**Comment by jpyen** [comment]
For example if you want to write the output to somewhere else other than disk. For example a remote file system or object storage, or if you want to attach it to an email. All those libraries enabling such will require []byte input.

**Comment by Koooooo-7** [comment]
> For example if you want to write the output to somewhere else other than disk. For example a remote file system or object storage, or if you want to attach it to an email. All those libraries enabling such will require []byte input.
> 

But for what this lib required.
It's not a pure operation all in memory. You always need a place/tmp-dir to store the file with a Chrome runtime.
There is only a simple extra IO to get what you want.
I suppose we don't need make things complicated such as experting the output stream in the lib for now.

Thx for ur suggestion and idea.
