### ISSUE TITLE
Does it support Tree chart?

### ISSUE THREAD

**Issue by beto20** [go-echarts/snapshot-chromedp#17]
Hello, 

I am trying to render a Tree chart to a png image, but the result does not match the HTML. I tried reducing the dimensions of the chart and simplifying it to one node, but I encountered the same problem. I also added custom configurations but got the same result. I would like to know if this library supports tree charts, or if it only supports Line and Bar charts. I will send the code, the image, and the HTML result. Additionally, I am using the example of a tree chart.
https://go-echarts.github.io/go-echarts/#/en-us/charts/tree

Thanks for your attention

Code:
```
func main() {
	page := components.NewPage()
	page.AddCharts(
		treeBase(),
	)

	y := render.NewSnapshotConfig(page.RenderContent(), "test2.png", SetConfig())
	err := render.MakeSnapshot(y)
	if err != nil {
		log.Fatalf("Failed to create snapshot: %v", err)
	}

	log.Println("Snapshot created successfully!")

}

func SetConfig() render.SnapshotConfigOption {
	return func(config *render.SnapshotConfig) {
		config.Renderer = "canvas"
		config.Path = "."
		config.FileName = "test2"
		config.Suffix = "png"
		config.Quality = 1
		config.HtmlPath = "."
		config.KeepHtml = true
	}
}

```

Image result:
![image](https://github.com/user-attachments/assets/bc4e6f42-870b-41dc-bc35-c9daefc7ff6f)

Html result:
<img width="1737" alt="image" src="https://github.com/user-attachments/assets/c2a308f9-91d0-4364-9dc2-b6841a3eecff">

**Comment by beto20** [comment]
I found a solution. After checking the chromedp library (https://github.com/chromedp/chromedp), I noticed that there is a function called ```Sleep(time.Duration)```. This function allows the process to wait until the image is rendered, allowing me to capture a complete image that matches the HTML.

I will attach the image where I added the code, along with some images of the tree, treemap, and graph, because this issue occurs not just with the tree chart

source code:
![image](https://github.com/user-attachments/assets/c198ed58-c85a-471d-9205-5aaef62c6876)

image tree result:
![image](https://github.com/user-attachments/assets/632d2024-6d6c-4fe4-b57e-63f633973a28)

image treemap result:
![image](https://github.com/user-attachments/assets/c4b81ce2-cebc-4d61-b51a-7204ef7a6044)

image graph result:
![image](https://github.com/user-attachments/assets/8d1ba610-2246-44b9-99ef-2ed8387a8199)

**Comment by Koooooo-7** [comment]
Hi @beto20 , sorry for the delay!
I guess you may not set the `Animation to false`, so you get the snapshot for empty. isn't it?

**Comment by Koooooo-7** [comment]
closed as outdate, kindly open a new one or reopen it if it needs.
