### ISSUE TITLE
snapshot-chromedp returning a partial plotted image.

### ISSUE THREAD

**Issue by Tusamarco** [go-echarts/snapshot-chromedp#6]
Hi, first of all thanks for the work done in the whole go-echart project.
Second ... consider I am not a GO expert developer so ... stay with me ;) 

I am testing the snapshot, and keeping the generated html for debug. 
What happens is that the saved image on file is like this:
![image](https://github.com/go-echarts/snapshot-chromedp/assets/5564455/667c1d26-402f-4642-98eb-808792d44b51)

While the html generated is correct:
![image](https://github.com/go-echarts/snapshot-chromedp/assets/5564455/139b642a-189c-4dff-be94-e4dfbfbe4da3)

the code is mainly as the example:
```golang
func (Graph *GraphGenerator) Test4() {
	barSetToolbox := barSetToolbox()
	MakeChartSnapshot(barSetToolbox.RenderContent(), "my-bar-title.png")
}
```

gomod imports:
```golang
        github.com/go-echarts/go-echarts/v2 v2.4.0-rc1
	github.com/chromedp/cdproto v0.0.0-20231011050154-1d073bb38998 // indirect
	github.com/chromedp/chromedp v0.9.3 // indirect
	github.com/chromedp/sysutil v1.0.0 // indirect
        github.com/go-echarts/snapshot-chromedp v0.0.1
```

Any clue where I should focus to discover what is going on?

**Comment by Tusamarco** [comment]
updated to latest:
```golang
	github.com/chromedp/cdproto v0.0.0-20240226204813-532e667d868f
	github.com/chromedp/chromedp v0.9.5
	github.com/chromedp/sysutil v1.0.0
```
no difference

**Comment by Tusamarco** [comment]
@Koooooo-7 any idea or suggestions?

**Comment by Koooooo-7** [comment]
Hi @Tusamarco. Sorry for the delay to resp.
I suppose that your didn't disable the chart Animation config.
Plz check the example in README. :)

**Comment by Tusamarco** [comment]
Oh yesss 
I did and I comment it out  ...
thanks I feel quite silly
