### ISSUE TITLE
[documents]readme docs add reminder about charts.WithAnimation(false)

### ISSUE THREAD

**Issue by JamesBrianD** [go-echarts/snapshot-chromedp#8]
Description:
When I want to use this respositry to draw a line.jpg with go-echarts, there is no line in the graph.

```go
func lineTooltip() *charts.Line {
	line := charts.NewLine()
	line.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "tooltip options"}),
		charts.WithLegendOpts(opts.Legend{Right: "80px"}),
	)
	line.SetXAxis(weeks).
		AddSeries("Category A", generateLineItems()).
		AddSeries("Category B", generateLineItems())
	return line
}
```

I think the readme document needs to add a reminder and charts.WithAnimation(false) must be used to correctly render images.

**Comment by Koooooo-7** [comment]
Hi, @RamezesDong , thx for your suggestion, I believe we already add it in README example, do you mean that  it should be more prominent? I gonna do the update.

https://github.com/go-echarts/snapshot-chromedp/blob/f313824ecb7eb615a8e70e2c03e282539c1878cd/README.md?plain=1#L86

**Comment by JamesBrianD** [comment]
Thanks! I think this comment is enough.
